-- Add Gemini-generated content columns to card_guessing table
-- These columns store AI-generated kitchen object images, descriptions, and memories

ALTER TABLE card_guessing
ADD COLUMN IF NOT EXISTS kitchen_images TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS kitchen_descriptions TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS kitchen_memories TEXT[] DEFAULT '{}';

-- Add comments to document the columns
COMMENT ON COLUMN card_guessing.kitchen_images IS 'Array of base64-encoded kitchen object images generated by Gemini';
COMMENT ON COLUMN card_guessing.kitchen_descriptions IS 'Array of descriptions of the kitchen objects';
COMMENT ON COLUMN card_guessing.kitchen_memories IS 'Array of fake memories associated with each kitchen object';
